### ISSUE TITLE
Gem release?

### ISSUE THREAD

**Issue by jduff** [omniauth/omniauth-okta#13]
Would it be possible to get a new gem released? It looks like a few patches have been merged which means I can get off the fork I was using, would be great to move over to a released version of the gem as well.

Thanks!

**Comment by Kuraiou** [comment]
Agreed, 0.1.2 would be much appreciated.

**Comment by attenzione** [comment]
please publish to rubygems 0.1.3, it's already created

**Comment by Serneum** [comment]
@dandrews can we get a new release now that the [OmniAuth 2.0](https://github.com/dandrews/omniauth-okta/pull/16) changes have been merged in?

**Comment by dandrews** [comment]
Would someone like to take this project over? As great as they are, I'm no longer working with Ruby, Okta, Omniauth.

**Comment by Serneum** [comment]
@dandrews Would it be worthwhile to transfer ownership to the OmniAuth organization, as mentioned in #15? If not, I can take ownership and see if the CoverMyMeds organization can own it.

**Comment by jduff** [comment]
👍 to moving it to the OmniAuth organization. I'm happy to help with this as I'm still using the gem, but under the OmniAuth org seems more future proof than moving it to another individual.

**Comment by BobbyMcWho** [comment]
Reading [this doc](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#about-repository-transfers) it looks like whoever transfers it will need rights to create a repo in that org. If you like, you can transfer this repo to me in the interim and I will handle getting it into the OmniAuth Org

**Comment by dandrews** [comment]
Thanks everyone. Much appreciated. I really like the idea of transferring to the OmniAuth org. @BobbyMcWho I'll transfer it to you. Thank you again.

**Comment by dandrews** [comment]
@BobbyMcWho - I get the following when I try to transfer: BobbyMcWho/omniauth-okta already exists

**Comment by BobbyMcWho** [comment]
I just realized that I have a fork so I can't take it. I invited you to join the OmniAuth org, which you can join, then transfer to the org, then leave the org if you like

**Comment by dandrews** [comment]
Ok cool thank you will do.

**Comment by BobbyMcWho** [comment]
@dandrews thanks for transferring that. If you wouldn't mind passing push rights on [rubygems](https://rubygems.org/gems/omniauth-okta) as well that'd be great 😄

**Comment by dandrews** [comment]
@BobbyMcWho can do - I added you as an owner on rubygems, feel free to add whoever else you think should be added.

**Comment by BobbyMcWho** [comment]
Appreciate it!

**Comment by BobbyMcWho** [comment]
I have released [0.1.3](https://github.com/omniauth/omniauth-okta/releases/tag/v0.1.3) based on [this commit](https://github.com/omniauth/omniauth-okta/commit/7246c02a8ccf9718365f0d34ae70854ffe75b5f3)

I have released [1.0.0](https://github.com/omniauth/omniauth-okta/releases/tag/v1.0.0)  based on [this commit](https://github.com/omniauth/omniauth-okta/commit/bd8481079e52572ea0d27e7bbfb96d9f53d7f4ea) 

Both releases can be found on [rubygems](https://rubygems.org/gems/omniauth-okta)

**Comment by dandrews** [comment]
You rock. Thank you!
