### ISSUE TITLE
/oauth2/v1/userinfo URL is hard-coded

### ISSUE THREAD

**Issue by matthewkrom** [omniauth/omniauth-okta#6]
Hello,

I notice /oauth2/v1/userinfo in #raw_info is a hard-coded URL. I have a case where it needs to include the auth server ID e.g. /oauth2/<auth-server-id-key>/v1/userinfo.  authorize_url and token_url are both configurable through client_options.  Would it make sense to add userinfo_url to this list? I could submit a pull request, but first wanted to ask for feedback, or if I'm missing something.

**Comment by dandrews** [comment]
That's a fair point. Please submit a pull request that abstracts the URL/domain into a variable/config var.
