### ISSUE TITLE
Publish gem with client_options fix

### ISSUE THREAD

**Issue by jgable** [omniauth/omniauth-okta#7]
Hi, thanks for your work on this gem. I noticed that you merged in the fix for client_options in #1 but it doesn't look like the gem has been updated with those fixes. 

Can you publish a new version with these fixes? I'm running into a `JWT::InvalidIssuerError` because the site url isn't matching.

**Comment by mark-cooper** [comment]
:+1: I have an app / bundler environment that supports pulling from rubygems but not via git so an updated release would be greatly appreciated :smile:

**Comment by douglasrlee** [comment]
yes, please publish

**Comment by bugthing** [comment]
yes, can I add my appreciation for the changes in master (as they fixed my issue). Also it would be great to have a new gem version release on rubygems.org
